services:
  - type: worker
    name: telegram-deal-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8213067607:AAHwbBRsKRtjtqwceiVQqcSii-tSGit6JNA
